export const sidebarListItems = [
  {
    listIconDark: "/images/leftsidebar-icon/c-1.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-1.svg",
    onHighlight: "/images/s-icon-10.svg",
    alt: "Favorites",
    listText: "Favorites",
    to: "/favorites",
    state: "isFavoritesOpen,",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-2.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-2.svg",
    onHighlight: "/images/icon-1.svg",
    alt: "Recents",
    listText: "Recents",
    to: "/recents",
    state: "isRecentsOpen",
  },
  {
    listIconDark: "/images/sidebar-poker.svg",
    listIconLight: "/images/Vectorrecents.svg",
    onHighlight: "/images/s-icon-9.svg",
    alt: "Promotions",
    listText: "Promotions",
    to: "/promotions",
    state: "isPromotionsOpen",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-3.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-3.svg",
    onHighlight: "/images/s-icon-8.svg",
    alt: "Originals",
    listText: "Originals",
    to: "/originals",
    state: "item1",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-4.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-4.svg",
    onHighlight: "/images/s-icon-7.svg",
    alt: "Slots",
    listText: "Slots",
    to: "/slots",
    state: "item2",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-5.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-5.svg",
    onHighlight: "/images/s-icon-6.svg",
    alt: "New Releasesd",
    listText: "New Releases",
    to: "/new-release",
    state: "item3",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-6.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-6.svg",
    onHighlight: "/images/icon-2.svg",
    alt: "Live Casino",
    listText: "Live Casino",
    to: "/live-casino",
    state: "item4",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-7.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-7.svg",
    onHighlight: "/images/icon-3.svg",
    alt: "Fish Games",
    listText: "Fish Games",
    to: "fish-games",
    state: "item5",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-8.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-8.svg",
    onHighlight: "/images/icon-4.svg",
    alt: "Table Games",
    listText: "Table Games",
    to: "/table-games",
    state: "item6",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-9.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-9.svg",
    onHighlight: "/images/icon-5.svg",
    alt: "Roulette",
    listText: "Roulette",
    to: "/roulette",
    state: "item7",
  },
  {
    listIconDark: "/images/leftsidebar-icon/c-10.svg",
    listIconLight: "/images/leftsidebar-icon/light-c-10.svg",
    onHighlight: "/images/s-icon-1.svg",
    alt: "Blackjack",
    listText: "Blackjack",
    to: "/blackjack",
    state: "item8",
  },
  {
    listIconDark: "/images/All Games.svg",
    listIconLight: "/images/All Games-d.svg",
    onHighlight: "/images/All Games-d.svg",
    alt: "All Games",
    listText: "All Games",
    to: "/all-games",
  },
  {
    listIconDark: "/images/Refer A Friend.svg",
    listIconLight: "/images/Refer A Friend-d.svg",
    onHighlight: "/images/Refer A Friend-d.svg",
    alt: "Refer a Friend",
    listText: "Refer a Friend",
    to: "/refer-friend",
  },
  {
    listIconDark: "/images/Leaderboard.svg",
    listIconLight: "/images/Leaderboar-d.svg",
    onHighlight: "/images/Leaderboar-d.svg",
    alt: "Leaderboard",
    listText: "Leaderboard",
    name: "Leaderboard",
    to: "/",
  },
  {
    listIconDark: "/images/sidebar-table.svg",
    listIconLight: "/images/g-2.svg",
    alt: "Leaderboard",
    listText: "Leaderboard",
    to: "#",
  },
  {
    listIconDark: "/images/sidebar-home.svg",
    listIconLight: "/images/g-2.svg",
    listText: "All Games",
    alt: "All Games",
    to: "/",
  },
  {
    listIconDark: "/images/sidebar-casino.svg",
    listIconLight: "/images/g-2.svg",
    listText: "Refer a Friend",
    alt: "Refer a Friend",
    to: "/",
  },
  {
    listIconDark: "/images/sidebar-table.svg",
    listIconLight: "/images/g-2.svg",
    alt: "Leaderboard",
    listText: "Leaderboard",
    to: "#",
  },
  {
    listIconDark: "/images/sidebar-hr.svg",
    listIconLight: "/images/g-2.svg",
    alt: "HR icon",
    listText: "HR Original",
    to: "#",
  },
  {
    listIconDark: "/images/sidebar-slot.svg",
    listIconLight: "/images/g-2.svg",
    listText: "Video Slots",
    alt: "Video Slots icon",
    to: "#",
  },
  {
    listIconDark: "/images/sidebar-slot3.svg",
    listIconLight: "/images/g-2.svg",
    listText: "Slots3",
    alt: "Slots icon",
    to: "#",
  },
  {
    listIconDark: "images/sidebar-favorites.svg",
    listIconLight: "/images/g-2.svg",
    listText: "Favorites",
    alt: "Favorites icon",
    to: "#",
  },
];

export const intialSidebarItemsState = [
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
  { isOpen: false },
];

export const userListItems = [
  {
    content: "HEADER.DEPOSIT",
    to: "/user/deposit",
    src: "/images/deposit.svg",
    alt: "Deposit Icon",
  },
  {
    content: "HEADER.WITHDRAW",
    to: "/user/withdraw",
    src: "/images/withdrawal.svg",
    alt: "Withdrawal Icon",
  },
  {
    content: "HEADER.BONUS",
    to: "/user/bonus",
    src: "/images/bonus.svg",
    alt: "Bonus Icon",
  },
  {
    content: "HEADER.REFERRAL",
    to: "/user/referral",
    src: "/images/Referral.svg",
    alt: "Referral Icon",
  },
];

export const languageMenu = [
  {
    language: "English",
    flag: "/images/uk-flag-svg.svg",
    alt: "EN",
    value: "en",
  },
  {
    language: "Español",
    flag: "/images/spain-flag-svg.svg",
    alt: "ES",
    value: "es",
  },
];

export const languageOptions = [
  {
    label: "English",
    value: "en",
  },
  {
    label: "Español",
    value: "es",
  },
];
